### ISSUE TITLE
WP Job Manager and stability?

### ISSUE THREAD

**Issue by tripflex** [OllieJones/index-wp-mysql-for-speeed#16]
First off, this is amazing, thank you for all your hard work on this project!

Quick background:
So i've worked on the WP Job Manager project for well over 8+ years now and one consistent bottleneck I find is around the `postmeta` and how queries are both built (and then obviously the db structure that wasn't necessarily meant for it).

With this plugin i've found that it can reduce the query (for example below) from **2s** down to **500ms** which is AMAZING! Especially because the query below is a basic example (they can get more complex).  Outside of completely rewriting how queries are generated, I was thinking about potentially starting to recommend this to users, and wanted to see if you believe everything is in a stable state to do so?

I did read all the documentation links and everything looks like it should be, I just wanted to double check with you before starting to recommend this as it could result in a very large influx of users.

Obviously they will all need to do their own due diligence for databases (backup, engine, etc), but figured I would just say THANK YOU and get your opinion?

Thanks again!

### Example:

As an example, this is the `meta_query` from a search for listings:
```
array (
  0 => 
  array (
    'relation' => 'OR',
    0 => 
    array (
      'key' => '_candidate_single_field',
      'value' => 'single',
      'compare' => '=',
    ),
    1 => 
    array (
      'key' => '_candidate_single_field',
      'compare' => 'NOT EXISTS',
    ),
  ),
  1 => 
  array (
    'relation' => 'OR',
    0 => 
    array (
      'relation' => 'AND',
      0 => 
      array (
        'key' => '_rate_min',
        'value' => '0',
        'type' => 'NUMERIC',
        'compare' => '>=',
      ),
      1 => 
      array (
        'key' => '_rate_min',
        'value' => '100',
        'type' => 'NUMERIC',
        'compare' => '<=',
      ),
    ),
    1 => 
    array (
      'key' => '_rate_min',
      'compare' => 'NOT EXISTS',
    ),
  ),
  2 => 
  array (
    'relation' => 'OR',
    0 => 
    array (
      'relation' => 'AND',
      0 => 
      array (
        'key' => '_candidate_age',
        'value' => '0',
        'type' => 'NUMERIC',
        'compare' => '>=',
      ),
      1 => 
      array (
        'key' => '_candidate_age',
        'value' => '100',
        'type' => 'NUMERIC',
        'compare' => '<=',
      ),
    ),
    1 => 
    array (
      'key' => '_candidate_age',
      'compare' => 'NOT EXISTS',
    ),
  ),
)
```

That results in SQL query such as this:
```
SELECT 
  SQL_CALC_FOUND_ROWS wp_posts.* 
FROM 
  wp_posts 
  LEFT JOIN wp_postmeta ON (
    wp_posts.id = wp_postmeta.post_id
  ) 
  LEFT JOIN wp_postmeta AS mt1 ON (
    wp_posts.id = mt1.post_id 
    AND mt1.meta_key = '_candidate_single_field'
  ) 
  LEFT JOIN wp_postmeta AS mt2 ON (wp_posts.id = mt2.post_id) 
  LEFT JOIN wp_postmeta AS mt3 ON (wp_posts.id = mt3.post_id) 
  LEFT JOIN wp_postmeta AS mt4 ON (
    wp_posts.id = mt4.post_id 
    AND mt4.meta_key = '_rate_min'
  ) 
  LEFT JOIN wp_postmeta AS mt5 ON (wp_posts.id = mt5.post_id) 
  LEFT JOIN wp_postmeta AS mt6 ON (wp_posts.id = mt6.post_id) 
  LEFT JOIN wp_postmeta AS mt7 ON (
    wp_posts.id = mt7.post_id 
    AND mt7.meta_key = '_candidate_age'
  ) 
WHERE 
  1 = 1 
  AND (
    (
      (
        wp_postmeta.meta_key = '_candidate_single_field' 
        AND wp_postmeta.meta_value = 'single'
      ) 
      OR mt1.post_id IS NULL
    ) 
    AND (
      (
        (
          mt2.meta_key = '_rate_min' 
          AND Cast(mt2.meta_value AS signed) >= '0'
        ) 
        AND (
          mt3.meta_key = '_rate_min' 
          AND Cast(mt3.meta_value AS signed) <= '100'
        )
      ) 
      OR mt4.post_id IS NULL
    ) 
    AND (
      (
        (
          mt5.meta_key = '_candidate_age' 
          AND Cast(mt5.meta_value AS signed) >= '0'
        ) 
        AND (
          mt6.meta_key = '_candidate_age' 
          AND Cast(mt6.meta_value AS signed) <= '100'
        )
      ) 
      OR mt7.post_id IS NULL
    )
  ) 
  AND wp_posts.post_type = 'resume' 
  AND (
    (wp_posts.post_status = 'publish')
  ) 
GROUP BY 
  wp_posts.id 
ORDER BY 
  wp_posts.post_title DESC 
LIMIT 
  0, 10
```

**Comment by rjasdf** [comment]
I'm glad that you are so happy about the performance boost we have provided you.
I can give you a big hint.  (But I don't know if it is possible within the constraints of the frameworks that are involved).
It looks like the query says (speaking in MySQL):       AND (age BETWEEN 0 AND 100) OR age IS NULLThat smells like the user "does not care".
So, my hint is to leave off the expression completely!  Why?  Well, neither WP nor MySQL is smart enough to realize that that the expression adds nothing to the filtering.  So it dutifully fetches "age", checks it for that range and checks for NULLness.  A lot of work, especially when the result has no impact on the whole query.
You were excited about 500ms.  Well, to me, that is "slow", and I feel the need to speed it up.  Eliminating "don't cares" will go some distance toward decreasing the 500.
Let me back up and paint a bigger picture.
WP uses a schema design that is called "Entity-Attribute-Value" (or EAV).  Its great selling point is the flexibility -- you can add 'age', 'cost', 'size', 'F-stop', 'engine displacement', 'description', etc, etc.  Whatever you want.  But it comes at a cost.  My one line of SQL started with it is about 20 lines of that tree structure below, which turned into about 10 lines of EAV SQL in WP.  And, as I point out, even my line can be shrunk to zero by some logic that you can provide.
But my one line comes at a different cost -- It requires that "age" be a column in the table.  That wrecks the flexibility of adding lots of arbitrary attributes.  While "age" could be indexed to improve performance, what about "rate_min" and all the other things.  Databases work well if there is less flexibility.  But you need flexibility (I assume).  Certainly WP (and derivatives like Woocommerce) depend on the flexibility of EAV.
Another point is this gibberish:  "AND Cast(mt2.meta_value AS signed) >= '0'" -- That is pointing out that the "age" is really numeric and it needs to be compared as such. Otherwise, you get nonsense like "2" is bigger than "10" -- because that is what happens when comparing strings. EAV is clumsy when handling numbers.
Your 'simple' query requires that the entire dataset be scanned. Databases don't like that. They like "indexes". Are you old enough to know what a physical "dictionary" was? When you looked up a word, did you scan page by page until you found the word? No, you could open to about where the word would be, the flip forward or backward quickly until you get to the right page. That's what an "index" brings to the table. EAV, in most cases, must scan page by page. Computers are fast, so it is "only" 500ms.
I have been optimizing code for decades.  Most recently, I have focused on MySQL.  stackoverflow.com is littered with WP users asking how to speed up their queries; pretty soon I noticed what was going on in wp_postmeta.  And when I found that they had not even created the optimal indexes, I wrote a blog on how to improve the indexes.  Eventually Ollie noticed and turned my blog into a plugin.
PS, there is another optimization that the Plugin cannot achieve:
GROUP BY   wp_posts.id 
ORDER BY   wp_posts.post_title DESC 
would run faster with this because this can do the two steps with a single sort instead of two.
GROUP BY  wp_posts.post_title,      wp_posts.id 
ORDER BY  wp_posts.post_title DESC, wp_posts.id DESC 
Back to your Question...  "Is the plugin stable enough to recommend...?".* I have addressed at least 41 questions about WP since 2016.* I blogged about how to build better indexes in 2017.* Ollie can say how many copies of the Plugin have been downloaded.During all that, I remember only one or two hiccups; they seem to be resolved.
Rick Jamesemail: ***@***.***

**Comment by OllieJones** [comment]
Thanks for the kind words. 

Our indexes are designed to handle the use case shown in your example query. Here's a tech writeup. https://www.plumislandmedia.net/index-wp-mysql-for-speed/tables_and_keys/

Rick is right about writing your queries to avoid using ranges on meta_value columns whenever you can.
Stuff like this, as he mentioned, is necessarily laborious in WordPress's EAV table design.

    AND Cast(mt2.meta_value AS signed) BETWEEN 0 AND 99

Rick is right about a lot of stuff.  :-)

Version 1.4.1 is about to roll.  I've been whaling on a lot of MySQL version compatibility problems, and compatibility with various database caching plugins. 

Give it a try and let us know how it goes.

**Comment by tripflex** [comment]
@rjasdf thank you so much for the detailed explanation!! I've actually read your stuff probably 5 times just to get a better understanding of everything (once I noticed all the slow queries).

To answer you guys questions, the idea behind the fields like `_candidate_age` ... what is happening here is that this is an optional field when a listing is submitted, so some listings will have a value (and some will not).  

What we've found is that most users want to "include" listings that do not have this value set, but also return listings that are within a specific range.  This is kinda the reason for the clunky queries, because we're dynamically generating the `meta_query` sent to `WP_Query` to inject the `NOT EXISTS` which WordPress turns into the `NULL` statement.

For an initial release was just trying to optimize things as much as possible without having to modify the actual query itself , as these are setup dynamically by the end user when configuring "what" filters they want to show on their site.

Unfortunately with the way that meta is stored in WordPress as well, the value is stored as a string, so to do the numeric comparison we have to cast the value (at least from my testing that's what i've found).

Thank you though for pointing out the use of `BETWEEN` instead of having two `OR` queries, will definitely make that modification to try and optimize those type of queries.

Again thank you @rjasdf and @OllieJones you guys have been tremendously helpful for me in this project now that i've had to really dive into dealing with the actual queries, both this plugin and the documentation/blog posts have been SUPER helpful!!

**Comment by rjasdf** [comment]
(** below)
Rick Jamesemail: ***@***.***
 

    On Wednesday, January 19, 2022, 07:38:32 AM PST, Myles McNamara ***@***.***> wrote:  
 
 


@rjasdf thank you so much for the detailed explanation!! I've actually read your stuff probably 5 times just to get a better understanding of everything (once I noticed all the slow queries).
To answer you guys questions, the idea behind the fields like _candidate_age ... what is happening here is that this is an optional field when a listing is submitted, so some listings will have a value (and some will not).
** I was assuming that when the user (who entered the data into the database) left out an age range, then all rows with any "age" should be included (pending other filtering)
What we've found is that most users want to "include" listings that do not have this value set, but also return listings that are within a specific range. This is kinda the reason for the clunky queries, because we're dynamically generating the meta_query sent to WP_Query to inject the NOT EXISTS which WordPress turns into the NULL statement.

** I assumed that NULL means "decline to state" or "data not available", and the WHERE clause is choosing to include rows with NULL while filtering on "age" if an age is provided by the searcher.
** The (age... OR age IS NULL) is not easily optimized, primarily because of the OR.  I understand the need for the NULL check.

For an initial release was just trying to optimize things as much as possible without having to modify the actual query itself , as these are setup dynamically by the end user when configuring "what" filters they want to show on their site.
** If you are generating stuff in PHP, I can suggest a way to "build the WHERE on the fly", thereby making it easy to leave out any "age" tests when the searcher does not provide a range.
Unfortunately with the way that meta is stored in WordPress as well, the value is stored as a string, so to do the numeric comparison we have to cast the value (at least from my testing that's what i've found).


** I'm glad you understand this generic EAV problem when storing numbers.
Thank you though for pointing out the use of BETWEEN instead of having two OR queries, will definitely make that modification to try and optimize those type of queries.
** Don't worry about it -- the two AND'd tests is equivalent to BETWEEN.  That is, the Optimizer treats them as identical.  BETWEEN is cleaner for humans when writing SQL
Again thank you @rjasdf and @OllieJones you guys have been tremendously helpful for me in this project now that i've had to really dive into dealing with the actual queries, both this plugin and the documentation/blog posts have been SUPER helpful!!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
