### ISSUE TITLE
rekey without using lots of /tmp space?

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/index-wp-mysql-for-speeed#3]
Can we rekey with   https://dev.mysql.com/doc/refman/5.6/en/innodb-online-ddl-operations.html#online-ddl-index-operations

ALGORITHM = INPLACE  ??

If we drop a pk and add another one in the same ddl, we can use INPLACE.

**Comment by OllieJones** [comment]
testing could be a hassle

**Comment by rjasdf** [comment]
Short answer:
* Do not explicitly specify ALGORITHM=... 
* I suggest doing all alters (for a single table) in a single statement.
Long answer:
Changes to the PK always require a COPY, I think.  It is probably correct to try to do _all_ ALTERs in a single statement.  Here's my rationale:* COPY was implemented decades ago and perfected over the years.* It is (I assume) identical on MySQL and MariaDB.* It is simply (1) create a new, empty, table; (2) apply the schema changes; (3) copy all the rows; (4) RENAME TABLE.  (Details about Locking, which way to recreate secondary indexes, whether to do OrderBy on the logical Select, etc are omitted.)
Adding/dropping a secondary key gets into this puzzle:
I have yet to figure out the details of the new ALTERs...
* Is it always as good or better to combine multiple alters in a single ALTER statement?* If you mix two actions, will it do whichever is "slower".  (Eg, changing the PK and adding to an ENUM requires a full rebuild?)  (It seems like doing COPY is already implemented.  Meanwhile COPY would be faster than splitting up the actions.)* In the case of two "simple" actions, will it do both simultaneously INPLACE (or whatever)?  Or will it simply perform two separate ALTERs?  (It seems like the latter would be almost as fast, while being much simpler to implement.)* It _seems_ that leaving off ALGORITHM=... gives you the 'fastest' ALTER, but I don't know for sure.* A guess:  explicitly specifying ALGORITHM=... has two uses:  (*) You know better than the code (not likely in our general plugin) or (*) The default algo is broken and you need to avoid it.  (I have not heard of this happening.)* I strongly hope that doing multiple things in a single statement does not cause it to revert to COPY.* Etc.
I would launch into experimenting, but it is quite complex:* Many different combinations of ALTERs.* Many different versions of MySQL and MariaDB.* Need a table with some bulk to measure speed.  Actually may need different tables for different situations.* The algo names keep changing.  As does the syntax for requesting an algorithm.  (Yuck!)
Most of my contacts in Oracle/MariaDB have dried up, so I can't easily find the person to ask.
For PARTITION, I simply say "Except for these 5 use cases", do not partition a table."  Maybe ALTER can be summarized as "Simply throw all the changes into a single ALTER and don't specify any ALGORITHM.  (Exceptions:  you know better / regression)".
(Let me know if you have any insight into Alter that differs from what I say.)

Rick Jamesemail: ***@***.***
 

    On Thursday, December 9, 2021, 04:13:17 AM PST, Oliver Jones ***@***.***> wrote:  
 
 


Can we rekey with https://dev.mysql.com/doc/refman/5.6/en/innodb-online-ddl-operations.html#online-ddl-index-operations

ALGORITHM = INPLACE ??

If we drop a pk and add another one in the same ddl, we can use INPLACE.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OllieJones** [comment]
This from the 5.6 doc claims that `DROP PRIMARY KEY, ADD PRIMARY KEY (something)` can be done without /tmp.  https://dev.mysql.com/doc/refman/5.6/en/innodb-online-ddl-operations.html#online-ddl-primary-key-operations

Is it, to your knowledge, wrong?

You're right that a single ALTER TABLE is far better than a mess of them. 

As for PARTITIONs, no freakin' way I'm going to do that in a free plugin. People who have WordPress installations so big they can consider partitioned tables probably have the money to hire somebody from a first-class database administration consultancy.

**Comment by rjasdf** [comment]
That quote sounds fishy.  It also says:
Data is reorganized substantially, making it an expensive operation.

Restructuring the clustered index always requires copying table data. 

I can't imagine that the code is going to discover some obscure cases that should be simple.  Instead, I expect it to copy the entire table over.The one case they might handle is "no PK" --> "new auto_increment".  Even this needs to remove the 6-byte hidden PK and replace it with an up-to-8-byte Int.  If it is going from 6 to 8, there are likely to be wasteful block-splits.  6 to 4 would leave wasted space.  I would implement it as a sweep through the table in old-PK order, building a new block from some rows, then deleting the block(s) that are freed.But this does not allow for ROLLBACK -- a big DDL feature of 8.0.  So, it is back to simply doing ALGORITHM=COPY.  Maybe that ALTER got slower in 8.0 relative to 5.6.
Rick Jamesemail: ***@***.***
 

    On Monday, December 13, 2021, 10:42:39 AM PST, Oliver Jones ***@***.***> wrote:  
 
 


This from the 5.6 doc claims that DROP PRIMARY KEY, ADD PRIMARY KEY (something) can be done without /tmp. https://dev.mysql.com/doc/refman/5.6/en/innodb-online-ddl-operations.html#online-ddl-primary-key-operations

Is it, to your knowledge, wrong?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OllieJones** [comment]
Now we do all the reindexing for each table in one go, fixed along with #5. It's possible, but not certain, that this will avoid sloshing a lot of data into the temp directory,
