### ISSUE TITLE
Problem with elementor on pxe_options

### ISSUE THREAD

**Issue by martip07** [OllieJones/index-wp-mysql-for-speeed#30]
Hi,

I am getting the following message each time I want to enable the autoindex for pxe_options:

```
Index WP MySQL For Speed 1.4.4
Versions  Plugin:1.4.4 MySQL:8.0.23 WordPress:5.9.1 WordPress database:51917 php:8.0.15
Error Duplicate entry '_elementor_pro_license_data_fallback' for key 'pxe_options.PRIMARY' de la base de datos de WordPress para la consulta ALTER TABLE pxe_options ADD UNIQUE KEY option_id (option_id), ADD PRIMARY KEY (option_name)/**imfs-query-tag*569927966*/ realizada por ImfsDb::query
PHP Fatal error:  Uncaught ImfsException: [0]: Duplicate entry '_elementor_pro_license_data_fallback' for key 'pxe_options.PRIMARY' in ALTER TABLE pxe_options ADD UNIQUE KEY option_id (option_id), ADD PRIMARY KEY (option_name)/**imfs-query-tag*569927966*/

  thrown in /home/678264.cloudwaysapps.com/skhrdxhadm/public_html/wp-content/plugins/index-wp-mysql-for-speed/code/imsfdb.php on line 375
Fatal error: Uncaught ImfsException: [0]: Duplicate entry '_elementor_pro_license_data_fallback' for key 'pxe_options.PRIMARY' in ALTER TABLE pxe_options ADD UNIQUE KEY option_id (option_id), ADD PRIMARY KEY (option_name)/**imfs-query-tag*569927966*/

  thrown in /home/678264.cloudwaysapps.com/skhrdxhadm/public_html/wp-content/plugins/index-wp-mysql-for-speed/code/imsfdb.php on line 375
```

What can I do?

Regards,

**Comment by rjasdf** [comment]
Can you provide `SHOW CREATE TABLE pxe_options` before attempting to add the plugin?
Rick Jamesemail: ***@***.***

**Comment by OllieJones** [comment]
It looks like you have a duplicate value in `pxe_options.option_name`.  That's very strange, because [WordPress's standard table design](https://codex.wordpress.org/Database_Description#Table:_wp_options) for the options table forbids duplicate values in that column. Allowing duplicates may disrupt the functioning of many parts of WordPress. Plenty of code does 

     INSERT INTO wp_options (option_name, option_value, autoload) VALUES (?, ?, ?)
           ON DUPLICATE KEY UPDATE option_value=?, autoload=?

If your table definition allows duplicate option_names, this query pattern inserts many duplicates, and breaks your table.

Somehow, in your installation, the WordPress standard key `UNIQUE KEY option_name (option_name)` on that table must have been dropped or changed to a non-UNIQUE key. 

It's not the place of this plugin to correct that problem.  

You can use wp-cli to get a list of the indexes by putting this into a shell.

    wp index-mysql tables

**Comment by rjasdf** [comment]
Might the COLLATION have changed?
Rick Jamesemail: ***@***.***
 

    On Wednesday, March 9, 2022, 10:54:27 AM PST, Oliver Jones ***@***.***> wrote:  
 
 


It looks like you have a duplicate value in pxe_options.option_name. That's very strange, because WordPress's standard table design for the options table forbids duplicate values in that column. Duplicate option_names may disrupt the functioning of many parts of WordPress.

Somehow, in your installation, the WordPress standard key UNIQUE KEY option_name (option_name) on that table must have been dropped or changed to a non-UNIQUE key.

It's not the place of this plugin to correct that problem.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OllieJones** [comment]
Maybe the collation is goofed. The WordPress default is some case-insensitive collation. It's possible to change it when installing a new instance, or I suppose by doing some ALTER TABLE operations.  But in any case the `option_name` in this tix is all lower case ASCII, as is every `option_name` I've ever seen.

(They shoulda used ASCII for whatever_key and whatever_name columns, but ....)

**Comment by rjasdf** [comment]
Was one of the ALTERs MODIFYing (CHANGEing) a text column?
Rick Jamesemail: ***@***.***
 

    On Thursday, March 10, 2022, 05:56:49 AM PST, Oliver Jones ***@***.***> wrote:  
 
 


Maybe the collation is goofed. The WordPress default is some case-insensitive collation. It's possible to change it when installing a new instance, or I suppose by doing some ALTER TABLE operations. But in any case the option_name in this tix is all lower case ASCII, as is every option_name I've ever seen.

(They shoulda used ASCII for whatever_key and whatever_name columns, but ....)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
