### ISSUE TITLE
Getting slow query. What column should I index and what type of index?

### ISSUE THREAD

**Issue by melwong** [OllieJones/index-wp-mysql-for-speeed#32]
I'm using your plugin but I'm getting this slow query below.
```
# Query_time: 3.357236  Lock_time: 0.000054  Rows_sent: 1  Rows_examined: 107494
# Rows_affected: 0  Bytes_sent: 67
SET timestamp=1652612113;
SELECT COUNT(*) FROM et_term_relationships, et_posts WHERE et_posts.ID = et_term_relationships.object_id AND post_status IN ('publish') AND post_type IN ('acadp_listings') AND term_taxonomy_id = 15;
```

I think it's caused by a plugin I'm using with a custom post type. Could your plugin help to resolve this?

Any help is appreciated.

**Comment by rjasdf** [comment]
Ollie may have more insight, meanwhile, will you provide  SHOW CREATE TABLE et_term_relationships;  SHOW CREATE TABLE et_posts;so that we can check the indexes you have (presumably added by the plugin).
Also, how much RAM do you have, and what is the value of
  SHOW VARIABLES LIKE 'innodb_buffer_pool_size';
3.4 seconds for 107K rows _may_ be what is required.
Can you run the query twice in a row -- this would check for any "caching" effect.  It would be handy if you could use the "mysql" commandline tool since running the above commands, plus the running the SELECT are easy to do, and give you timing results immediately (without finding the slowlog).
Another diagnostic would be to run the query with "EXPLAIN" in front:
   EXPLAIN SELECT ... ((etc))
I can see two ways that the Optimizer might choose between for running the query; either should be reasonably good (if the indexes are 'correct'); EXPLAIN will tell us which way it chose.
Rick Jamesemail: ***@***.***
 

    On Tuesday, May 17, 2022, 07:28:44 AM PDT, melwong ***@***.***> wrote:  
 
 


I'm using your plugin but I'm getting this slow query below.
# Query_time: 3.357236  Lock_time: 0.000054  Rows_sent: 1  Rows_examined: 107494
# Rows_affected: 0  Bytes_sent: 67
SET timestamp=1652612113;
SELECT COUNT(*) FROM et_term_relationships, et_posts WHERE et_posts.ID = et_term_relationships.object_id AND post_status IN ('publish') AND post_type IN ('acadp_listings') AND term_taxonomy_id = 15;

I think it's caused by a plugin I'm using with a custom post type. What index (with what columns) should I create and what type of index should I use (PRIMARY KEY, UNIQUE, INDEX, FULLTEXT)?

Any help is appreciated.

**Comment by melwong** [comment]
> Ollie may have more insight, meanwhile, will you provide  SHOW CREATE TABLE et_term_relationships;  SHOW CREATE TABLE et_posts;so that we can check the indexes you have (presumably added by the plugin).

CREATE TABLE `et_term_relationships` (
  `object_id` bigint(20) unsigned NOT NULL DEFAULT 0,
  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT 0,
  `term_order` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`object_id`,`term_taxonomy_id`),
  KEY `term_taxonomy_id` (`term_taxonomy_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `et_posts` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `post_author` bigint(20) unsigned NOT NULL DEFAULT 0,
  `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_title` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'publish',
  `comment_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `ping_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `post_password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `post_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `to_ping` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `pinged` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content_filtered` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_parent` bigint(20) unsigned NOT NULL DEFAULT 0,
  `guid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `menu_order` int(11) NOT NULL DEFAULT 0,
  `post_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'post',
  `post_mime_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `comment_count` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `post_name` (`post_name`(191)),
  KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`),
  KEY `post_parent` (`post_parent`),
  KEY `post_author` (`post_author`),
  KEY `status_type` (`post_status`,`post_type`)
) ENGINE=MyISAM AUTO_INCREMENT=127803 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC

> SHOW VARIABLES LIKE 'innodb_buffer_pool_size';
134217728

> Can you run the query twice in a row -- this would check for any "caching" effect.  It would be handy if you could use the "mysql" commandline tool since running the above commands, plus the running the SELECT are easy to do, and give you timing results immediately (without finding the slowlog).
I ran it from HeidiSQL remote client (I'm not good with MySQL CLI) and the first query took maybe a second but second and third and etc were like instantaneous. I checked the slow log and it's not logged.

> Another diagnostic would be to run the query with "EXPLAIN" in front:    EXPLAIN SELECT ... ((etc))
Here you go - https://nimb.ws/ow1ebt

Btw, I'm using the Pro/paid version of this plugin - https://wordpress.org/plugins/advanced-classifieds-and-directory-pro/

**Comment by OllieJones** [comment]
With respect, I am closing this issue. Both my experience and Rick's (@rjasdf) are mostly with the newer InnoDB storage engine. You're still using the obsolete MyISAM engine. Please use our plugin to upgrade your storage engine and add the high-performance keys. If you still have problems, don't hesitate to open a new issue.

And, please keep in mind that there's no database magic that can make `COUNT()` miraculously fast.

**Comment by rjasdf** [comment]
I agree that MyISAM is likely to be a big factor in the performance problem.
When switching from InnoDB to MyISAM, two settings need to change:
key_buffer_size -- decrease to 40Minnodb_buffer_pool_size -- increase to 70% of _available_ memory (after accounting for other apps running on the same machine.  If you have less than 4GB, then 70% will be too big; how much RAM do you have?
I see from the Explain that it found 21K rows in the first table.  After changing to InnoDB, it is likely to still be 21K, but the change in the structure of indexes may help it be faster.
Potentially relevant blogs:Conversion to InnoDB:  http://mysql.rjweb.org/doc.php/myisam2innodbMemory allocation:  http://mysql.rjweb.org/doc.php/memory
Rick Jamesemail: ***@***.***
 

    On Wednesday, May 18, 2022, 06:49:13 AM PDT, Oliver Jones ***@***.***> wrote:  
 
 


With respect, I am closing this issue. Both my experience and Rick's ***@***.***) are mostly with the newer InnoDB storage engine. You're still using the obsolete MyISAM engine. Please use our plugin to upgrade your storage engine and add the high-performance keys. If you still have problems, don't hesitate to open a new issue.

**Comment by melwong** [comment]
I've yet to find the time to work on the proposed solutions but I appreciate all the inputs. Thanks so much. I'll keep you posted.
