### ISSUE TITLE
max_statement_time exceeded on ALTER TABLE wp_postmeta

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/index-wp-mysql-for-speeed#56]
[poprebels](https://wordpress.org/support/users/poprebels/) [reports](https://wordpress.org/support/topic/query-execution-was-interrupted-in-alter-table/) a timeout ("Query execution was interrupted") on the ALTER TABLE statement for wp_postmeta.

The max_statement_time variable on that server is set to 30 sec.

Workaround: do this with WP-CLI

```
echo "SET max_statement_time = 3600;" >/tmp/sql$$
wp index-mysql enable wp_postmeta --dryrun >>/tmp/sql$$
wp db query </tmp/sql$$
```

Possible fix: if max_statement_time is set to anything other than 0, try setting it to 0. If that fails try setting it to 3600. If that fails try setting it to 600.  (We need to figure out dbms version dependencies when coding this into the plugin.)

**Comment by rjasdf** [comment]
(Please note that max_statement_time is available only on Percona/MariaDB, not MySQL.)

Since the ALTER in question probably takes an amount proportional to the size of the table being modified, setting it to something other than 0 (= infinite) should be done only by a DBA who understands the impact.

To temporarily override the setting from somewhere else, do something like

    SET STATEMENT max_statement_time=3600 FOR ALTER ... ;
